### ISSUE TITLE
大佬，软件很好，很强大，正是需要的，但是好像竖版的照片有问题，能不能解决一下，谢谢了！

### ISSUE THREAD

**Issue by wjh1025** [3egirlsdream/Watermark.Win#1]
大佬，软件很好，很强大，正是需要的，但是好像竖版的照片有问题，能不能解决一下，谢谢了！

**Comment by 3egirlsdream** [comment]
1.2.0.0版本新增了旋转图片方向的功能，你更新下

**Comment by 3egirlsdream** [comment]
> 大佬，软件很好，很强大，正是需要的，但是好像竖版的照片有问题，能不能解决一下，谢谢了！

1.2.0.0版本新增了旋转图片方向的功能，你更新下
