### ISSUE TITLE
成品不错，但是设置里面的东西为什么只能编辑文字所有的东西？本身改不了？

### ISSUE THREAD

**Issue by zhaoqianbiao** [3egirlsdream/Watermark.Win#2]
成品不错，但是设置里面的东西为什么只能编辑文字左右的东西？本身改不了？
![Snipaste_2023-03-19_20-46-13](https://user-images.githubusercontent.com/69677477/226176078-afb8845a-0d98-4a83-9c54-8213a0153165.png)

**Comment by 3egirlsdream** [comment]
这里的文字只是预览示例，表示这个配置项代表哪个属性，选择后保存，重新导入图片会自动读取你图片对应的参数填充，如果没有填充成功，还是默认值说明你的图片导出时可能擦除了EXIF信息

**Comment by zhaoqianbiao** [comment]
> 这里的文字只是预览示例，表示这个配置项代表哪个属性，选择后保存，重新导入图片会自动读取你图片对应的参数填充，如果没有填充成功，还是默认值说明你的图片导出时可能擦除了EXIF信息

好的 明白
