### ISSUE TITLE
自动读取图片exif信息

### ISSUE THREAD

**Issue by owlabear** [3egirlsdream/Watermark.Win#3]
您好！在b站上见到了您的软件感到非常惊艳！请问未来是否有考虑加入一个自动读取照片exif信息的功能呢？类似于PS使用脚本添加exif一样，这样也许可以更加方便批量操作。

**Comment by 3egirlsdream** [comment]
这个功能一直是支持的，如果读取不到尝试查看图片属性，看图片的Exif信息是否在PS或LR导出时被擦除了
