### ISSUE TITLE
设置添加配置项，允许抹除导出后图片的EXIF信息

### ISSUE THREAD

**Issue by Doradx** [3egirlsdream/Watermark.Win#4]
作者您好，是否可以在设置中添加可选项，在将照片抹除EXIF信息后再导出？因为很多时候是分享到网络上，很多隐私信息（例GPS）不想附加到照片上。感谢

**Comment by Doradx** [comment]
此外是，本插件为啥要降低图片尺寸呀？

**Comment by 3egirlsdream** [comment]
> 

不会降低尺寸，可以选择原图导出

**Comment by 3egirlsdream** [comment]
升级到最新版本支持擦除元数据
